version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    networks:
      - iHRhub-network
    deploy:
      resources:
        limits:
          memory: 512M  # Limit the memory usage of the React app container to 512MB

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
    networks:
      - iHRhub-network
    deploy:
      resources:
        limits:
          memory: 512M  # Limit the memory usage of the NGINX container to 512MB

networks:
  iHRhub-network:
    driver: bridge
